title: Passionate software developer Sergey Glazyrin
description: > # this means to ignore newlines until "baseurl:"
  Sergey Glazyrin python javascript design patterns project management
permalink: ':title/'
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Sergey Glazyrin # add your name
author-img: me.jpg # add your photo
about-author: I am a passionate software develop who understands how to develop the things properly and how to implement features very fast
twitter: sergdev
facebook: sergey.glazyrin
github: sergeyglazyrindev
linkedin: https://www.linkedin.com/in/sergey-glazyrin-70066733
email: sergey.glazyrin.dev@gmail.com

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
